version: "3.9"

services:
  backend:
    build: ./server
    container_name: jwt-backend
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: jwt-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend